(()=>{
const rolePages={owner:['overview','files','terminal','backups','users','audit','integrations','labs','settings'],admin:['overview','files','terminal','backups','users','audit','integrations','labs','settings'],operator:['overview','files','terminal','backups','integrations','labs','settings'],member:['overview','files','labs','settings'],viewer:['overview','files','backups','labs','settings']};
const can=p=>(rolePages[me?.role]||['overview']).includes(p);const has=p=>me?.permissions?.includes('*')||me?.permissions?.includes(p);
const labIcon='<svg class="navico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M9 3h6M10 3v5l-5 9a2.5 2.5 0 0 0 2.2 4h9.6a2.5 2.5 0 0 0 2.2-4l-5-9V3"/><path d="M7.5 15h9"/></svg>';
const originalNav=window.nav,originalOpen=window.open,originalFiles=window.files,originalBackups=window.backups,originalSettings=window.settings,originalUsers=window.users;
function labs(){if(metricTimer){clearInterval(metricTimer);metricTimer=null}if(clockTimer){clearInterval(clockTimer);clockTimer=null}page='labs';nav();q('#title').textContent='Labs';q('#content').innerHTML='<div class="card glass wide" style="min-height:360px;display:grid;place-items:center;text-align:center"><div><div class="small">CLOUD OS LABS</div><h2>Coming Soon</h2><p class="muted">Experimental Cloud OS tools will appear here.</p></div></div>'}
window.nav=function(){let allowed=rolePages[me?.role]||['overview'];let f=x=>'<button data-p="'+x+'" class="'+(x===page?'active':'')+'">'+(x==='labs'?labIcon:icons[x])+'<span>'+x[0].toUpperCase()+x.slice(1)+'</span></button>';q('#nav').innerHTML=allowed.map(f).join('');q('#mobile').innerHTML=allowed.map(f).join('');document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{q('#mobile')?.classList.remove('open');q('#hamb')?.setAttribute('aria-expanded','false');window.open(b.dataset.p)})};
window.open=function(p){if(!can(p))p='overview';if(p==='labs')return labs();return originalOpen(p)};
function uploadProgress(path){let input=q('#uploadFile'),button=q('#uploadBtn');if(!input||!button||!has('files.write'))return;let box=document.createElement('div');box.id='uploadProgress';box.className='uploadProgress hidden';box.innerHTML='<div class="uploadProgressTop"><span id="uploadName">Preparing upload</span><b id="uploadPct">0%</b></div><div class="uploadTrack"><i id="uploadBar"></i></div>';button.parentElement.appendChild(box);input.onchange=()=>{let file=input.files?.[0];if(!file)return;let fd=new FormData();fd.append('file',file);box.classList.remove('hidden');q('#uploadName').textContent=file.name;q('#uploadPct').textContent='0%';q('#uploadBar').style.width='0%';button.disabled=true;let xhr=new XMLHttpRequest();xhr.open('POST','/api/upload?path='+encodeURIComponent(path));xhr.withCredentials=true;xhr.upload.onprogress=e=>{if(!e.lengthComputable)return;let pct=Math.min(100,Math.round(e.loaded/e.total*100));q('#uploadPct').textContent=pct+'%';q('#uploadBar').style.width=pct+'%'};xhr.onload=async()=>{button.disabled=false;if(xhr.status>=200&&xhr.status<300){q('#uploadPct').textContent='100%';q('#uploadBar').style.width='100%';setTimeout(()=>window.files(path),350)}else{let msg='Upload failed';try{let d=JSON.parse(xhr.responseText),er=d.detail?.error||d.error;msg=(er?.code?er.code+': ':'')+(er?.message||msg)}catch(_){}await notice('Upload failed',msg);box.classList.add('hidden')}};xhr.onerror=async()=>{button.disabled=false;box.classList.add('hidden');await notice('Upload failed','Network connection was interrupted during upload.')};xhr.send(fd)}}
window.files=async function(path=''){await originalFiles(path);if(me.role==='viewer'){q('#newFolder')?.remove();q('#newFile')?.remove();q('#uploadBtn')?.remove();q('#uploadFile')?.remove();document.querySelectorAll('[data-ren],[data-del],[data-share]').forEach(x=>x.remove());document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>window.open('/preview?path='+encodeURIComponent(b.dataset.edit),'_blank','noopener'))}else uploadProgress(path)};
async function viewerBackups(){let a=await api('/api/readonly/backups'),details=await Promise.all(a.map(async n=>{try{return await api('/api/readonly/backups/'+encodeURIComponent(n))}catch(_){return{name:n,legacy:true}}}));let fmt=n=>n==null?'Legacy backup':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';q('#content').innerHTML='<div class="card glass"><div class="sectionbar"><div><h3 style="margin:0">Backups</h3><div class="small">Read-only backup access</div></div></div><div class="list">'+(details.length?details.map(x=>'<div class="row"><span><b>'+E(x.name)+'</b><br><span class="small">'+E(fmt(x.total_bytes))+(x.file_count!=null?' · '+E(x.file_count)+' files':'')+'</span></span><span class="small">Read only</span></div>').join(''):'<div class="empty">No backups available.</div>')+'</div></div>'}
window.backups=async function(){if(me.role==='viewer')return viewerBackups();return originalBackups()};
function settingsTabs(tab){return '<div class="settings-tabs"><button class="btn '+(tab==='account'?'active':'')+'" data-lite-st="account">Account</button><button class="btn '+(tab==='about'?'active':'')+'" data-lite-st="about">About</button></div>'}
window.settings=async function(tab='account'){if(me.role==='owner')return originalSettings(tab);if(!['account','about'].includes(tab))tab='account';let tabs=settingsTabs(tab);if(tab==='account'){q('#content').innerHTML=tabs+'<div class="card glass"><h3>Account</h3><p class="muted">Signed in as @'+E(me.username)+' · '+E(me.role)+'. Change your own password here.</p><div class="form-grid"><input id="currentPass" type="password" placeholder="Current password"><input id="newPass" type="password" placeholder="New password (12+ characters)"></div><button id="changePassLite" class="btn primary" style="margin-top:10px">Change password</button></div>';q('#changePassLite').onclick=async()=>{try{await api('/api/account/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({current_password:q('#currentPass').value,new_password:q('#newPass').value})});await notice('Cloud OS','Password changed. Sign in again.');location.reload()}catch(e){await notice('Cloud OS',e.code+': '+e.message)}}}else{let d=await api('/api/system/details'),gb=n=>(n/1073741824).toFixed(2)+' GB',rows=[['System name',d.system_name],['Local IP','Hidden for this role'],['Operating system',d.os+' '+d.os_release],['Architecture',d.architecture],['Processor',d.processor],['CPU cores',d.cpu_physical_cores+' physical / '+d.cpu_logical_cores+' logical'],['RAM',gb(d.ram_total)],['Graphics',d.graphics],['Python',d.python],['Cloud OS',d.cloud_os_version]];q('#content').innerHTML=tabs+'<div class="card glass"><h3>About Cloud OS</h3><div class="list">'+rows.map(x=>'<div class="kv"><b>'+E(x[0])+'</b><code class="kvalue">'+E(x[1])+'</code><span></span></div>').join('')+'</div></div>'}document.querySelectorAll('[data-lite-st]').forEach(b=>b.onclick=()=>window.settings(b.dataset.liteSt))};
window.users=async function(){await originalUsers();document.querySelectorAll('option[value="admin"]').forEach(x=>x.remove());let all=await api('/api/users'),rows=[...document.querySelectorAll('#content .card:first-child .list .row')];all.forEach((u,i)=>{if(u.username==='admin'||!rows[i])return;let actions=rows[i].querySelector('.row-actions');if(!actions)return;let select=document.createElement('select');select.className='select';select.dataset.roleUser=u.username;select.innerHTML=['operator','member','viewer'].map(r=>'<option value="'+r+'" '+(u.role===r?'selected':'')+'>'+r[0].toUpperCase()+r.slice(1)+'</option>').join('');select.onchange=async()=>{let role=select.value;if(!await modal('Change role','<p class="muted">Change @'+E(u.username)+' to <b>'+E(role)+'</b>? Existing sessions will be signed out.</p>','Change role')){select.value=u.role;return}try{await api('/api/access/users/'+encodeURIComponent(u.username)+'/role',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})});window.users()}catch(e){select.value=u.role;await notice('Role update failed',e.code+': '+e.message)}};actions.prepend(select)})};
let style=document.createElement('style');style.textContent='.uploadProgress{flex:1 1 240px;min-width:220px;padding:10px 12px;border:1px solid #ffffff14;border-radius:13px;background:#090c13}.uploadProgressTop{display:flex;justify-content:space-between;gap:12px;font-size:12px;margin-bottom:7px}.uploadProgressTop span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.uploadTrack{height:6px;border-radius:99px;background:#ffffff12;overflow:hidden}.uploadTrack i{display:block;width:0;height:100%;background:#8fa2ff;transition:width .15s linear}';document.head.appendChild(style);
new MutationObserver(()=>document.querySelectorAll('option[value="admin"]').forEach(x=>x.remove())).observe(document.documentElement,{subtree:true,childList:true});
})();
