from .lab_defs_common import challenge,cmd,AWS_MAP
LABS=[
 challenge("M1","Cloud Fundamentals Challenge","Secure a small cloud tenant using Module 1 fundamentals.",[cmd("security scan","Findings: public bucket, wrong subnet, excessive role"),cmd("challenge fix public-bucket","Public bucket fixed.","fix-public-bucket"),cmd("challenge fix subnet","Workload placement corrected.","fix-subnet"),cmd("challenge fix role","Role reduced.","fix-role")]),
 challenge("M2","IAM Security Audit","Audit and remediate IAM weaknesses.",[cmd("iam audit","Findings: wildcard, old key, dormant admin"),cmd("challenge fix wildcard","Wildcard removed.","fix-wildcard"),cmd("challenge fix old-key","Old fake key revoked.","fix-old-key"),cmd("challenge fix dormant-admin","Dormant admin disabled.","fix-dormant-admin")]),
 challenge("M3","Secure the Network","Harden network exposure and monitoring.",[cmd("security scan ports","Findings: ssh public, db public, scanner allowed"),cmd("challenge fix ssh","SSH restricted.","fix-ssh"),cmd("challenge fix db","Database privatized.","fix-db"),cmd("challenge block scanner","Synthetic scanner blocked.","block-scanner")]),
 challenge("M4","Harden Compromised Server","Harden a compromised virtual compute workload.",[cmd("instance inspect web-01","Findings: outdated, root container, metadata proxy, debug port"),cmd("challenge patch server","Virtual patches applied.","patch-server"),cmd("challenge protect metadata","Metadata protected.","protect-metadata"),cmd("challenge harden container","Container hardened.","harden-container"),cmd("challenge close debug","Debug port closed.","close-debug")]),
 challenge("M5","Secure Exposed Storage","Secure object storage and sensitive data.",[cmd("security scan","Findings: public bucket, wildcard access, unencrypted restricted data"),cmd("challenge private bucket","Bucket made private.","private-bucket"),cmd("challenge least-privilege","Bucket permissions minimized.","least-privilege"),cmd("challenge encrypt data","Restricted data encrypted.","encrypt-data")]),
]
FINAL_COMMANDS=[
 cmd("novacloud audit","10 findings: developer admin; old key; public database; 3306 public; unused SSH; outdated package; metadata exposure; root container; public bucket; unencrypted confidential data"),
 cmd("novacloud fix developer-admin","Developer admin removed.","fix-developer-admin"),cmd("novacloud fix old-key","Old fake key revoked.","fix-old-key"),cmd("novacloud fix public-database","Database moved private.","fix-public-database"),cmd("novacloud fix port-3306","3306 restricted internally.","fix-port-3306"),cmd("novacloud fix unused-ssh","Unused SSH closed.","fix-unused-ssh"),cmd("novacloud fix outdated-package","Virtual package updated.","fix-outdated-package"),cmd("novacloud fix metadata","Metadata protected.","fix-metadata"),cmd("novacloud fix root-container","Container changed to non-root.","fix-root-container"),cmd("novacloud fix public-bucket","Bucket made private.","fix-public-bucket"),cmd("novacloud fix encryption","Confidential data encrypted.","fix-encryption")]
marks=[c["mark"] for c in FINAL_COMMANDS if c.get("mark")]
LABS.append({"id":"FINAL-1","module":"FINAL","number":"Final","title":"NovaCloud Ltd. Final Module 1–5 Challenge","topic":"Cross-module cloud security investigation","difficulty":"Intermediate","estimated_minutes":45,"objective":"Find and remediate ten cloud-security misconfigurations across IAM, networking, compute, storage, and logs.","scenario":"NovaCloud Ltd. has ten intentional misconfigurations. Everything is synthetic and isolated.","theory":"Enumerate, prioritize, remediate, verify, and document. No Internet or host targets are contacted.","learn":["Cross-domain investigation","Risk prioritization","End-to-end verification"],"topology":"Identity + Network + Compute + Storage + Synthetic Logs","commands":FINAL_COMMANDS,"tasks":[{"id":f"FINAL-1-T{i+1}","title":m.replace('-',' ').title(),"required":m,"points":10,"hint":"Start with novacloud audit.","failure":f"Finding remains unresolved: {m.replace('-',' ')}."} for i,m in enumerate(marks)],"hints":["Run novacloud audit first.","Fix findings one at a time."],"common_mistakes":["Skipping enumeration","Fixing only one domain","Leaving data unencrypted"],"security_explanation":"All credentials, networks, services, buckets, logs and vulnerabilities are fictional sandbox state.","aws_mapping":sum(AWS_MAP.values(),[])})
