from .lab_defs_common import lab,cmd
LABS=[
lab("M3",1,"Build a Virtual Network","VPC/VNet and subnet placement","Place public and private workloads in correct simulated subnets.","web-server must be public; database-server must remain private.",[
 cmd("network show","vnet 10.10.0.0/16\npublic 10.10.1.0/24\nprivate 10.10.2.0/24"),cmd("network place web-server public","web-server -> public.","place-web-public"),cmd("network place database-server private","database-server -> private.","place-db-private"),cmd("network hosts","web-server 10.10.1.10\ndatabase-server 10.10.2.10")],"Intermediate"),
lab("M3",2,"Security Groups","Stateful virtual security groups","Allow only required web/database paths.","80/443 should be public; DB 3306 internal only; SSH not public.",[
 cmd("sg list","web:22 public,80 public,443 public\ndb:3306 public"),cmd("sg remove web 22 public","Removed public SSH.","block-public-ssh"),cmd("sg remove db 3306 public","Removed public DB.","remove-public-db"),cmd("sg add db 3306 internal","Added internal DB.","allow-internal-db"),cmd("sg test","web80/443=ALLOW; web22=DENY; db3306 public=DENY internal=ALLOW","test-sg")],"Intermediate"),
lab("M3",3,"Network ACL","Subnet-level ACLs","Allow web traffic and block a malicious LAB IP.","Subnet ACL must permit HTTP/HTTPS and deny 10.10.9.66.",[
 cmd("acl list","100 allow any\n* deny any"),cmd("acl allow tcp 80","Allowed 80.","allow-http"),cmd("acl allow tcp 443","Allowed 443.","allow-https"),cmd("acl block 10.10.9.66","Blocked synthetic source.","block-malicious-ip")],"Intermediate"),
lab("M3",4,"Open Port Investigation","Safe port exposure investigation","Scan a LAB target and close unnecessary exposed services.","web-server exposes SSH, DB, and debug services to the simulated Internet.",[
 cmd("scan web-server","22/tcp open\n80/tcp open\n443/tcp open\n3306/tcp open\n8080/tcp open"),cmd("ports close web-server 3306","3306 no longer public.","close-db-port"),cmd("ports close web-server 22","22 no longer public.","close-ssh-port"),cmd("ports close web-server 8080","8080 no longer public.","close-dev-port"),cmd("scan web-server verify","80/tcp open\n443/tcp open","rescan-web")],"Intermediate"),
lab("M3",5,"Network Exposure","Public/private exposure","Detect and fix a publicly exposed database.","A private database was accidentally made public.",[
 cmd("exposure show","web-server public\ndatabase-server PUBLIC (misconfigured)"),cmd("exposure set database-server private","database-server -> private.","privatize-db"),cmd("exposure test database-server internet","DENY","verify-db-private")],"Intermediate"),
lab("M3",6,"Network Security Monitoring","Synthetic network telemetry","Analyze synthetic traffic and identify suspicious patterns.","Logs contain normal traffic, denied requests, scanning, and repeated SSH attempts.",[
 cmd("netmon logs","ALLOW web 10.10.1.4:443\nDENY ssh 10.10.9.66\nSCAN 10.10.9.77 ports=22,80,443,3306\nAUTH_FAIL ssh count=12"),cmd("netmon filter denied","DENY ssh 10.10.9.66","filter-denied"),cmd("netmon suspicious","10.10.9.77 port-scan\n10.10.9.66 repeated-ssh","find-suspicious"),cmd("netmon block 10.10.9.77","Synthetic scanner blocked.","block-scanner")],"Intermediate")]
