from .lab_defs_common import lab,cmd
LABS=[
lab("M4",1,"Secure a Cloud Instance","Virtual instance hardening","Fix weak permissions, unnecessary port, default credentials, and outdated package.","web-01 is intentionally insecure inside the sandbox.",[
 cmd("instance inspect web-01","weak permissions\nport 3306 public\ndefault credential present\nopenssl outdated"),cmd("instance fix web-01 permissions","Permissions hardened.","fix-permissions"),cmd("instance fix web-01 port","Unnecessary public port removed.","fix-port"),cmd("instance fix web-01 credentials","Default fake credential removed.","fix-default-credential"),cmd("instance fix web-01 patch","Virtual package state updated.","fix-patch")],"Intermediate"),
lab("M4",2,"Open Ports","Compute service exposure","Identify and close public database/cache ports.","A server exposes SSH, HTTP, MySQL, and Redis.",[
 cmd("ports list web-01","22 SSH public\n80 HTTP public\n3306 MySQL public\n6379 Redis public"),cmd("ports close web-01 3306","3306 closed.","close-mysql"),cmd("ports close web-01 6379","6379 closed.","close-redis"),cmd("ports restrict web-01 22 admin-net","SSH restricted to admin-net.","restrict-ssh")],"Intermediate"),
lab("M4",3,"Patch Management","Virtual patch management","Find outdated packages and update only the sandbox package database.","web-01 has old nginx and openssl versions.",[
 cmd("packages list","nginx 1.20\nopenssl 1.1-old\nnovacloud-app 2.0"),cmd("packages outdated","nginx -> 1.26\nopenssl -> 3.x","find-outdated"),cmd("packages update nginx","Virtual nginx updated.","update-nginx"),cmd("packages update openssl","Virtual openssl updated.","update-openssl")],"Intermediate"),
lab("M4",4,"Instance Metadata Security","Metadata service protection","Stop an application from exposing simulated metadata credentials.","A vulnerable lab app proxies fake metadata from 169.254.169.254.",[
 cmd("metadata show","instance-id i-LAB123\nrole web-role\ncredential FAKE-TEMP-CREDENTIAL"),cmd("metadata exposure","application-proxy enabled","inspect-metadata"),cmd("metadata protect require-token","Token requirement enabled.","require-token"),cmd("metadata protect disable-proxy","Metadata proxy disabled.","disable-metadata-proxy")],"Intermediate"),
lab("M4",5,"Container Security","Rootless container security concepts","Harden an intentionally insecure sandbox container.","app-container runs as root with fake secret, public debug port, and weak volume permissions.",[
 cmd("container inspect app-container","user=root\nsecret=FAKE-SECRET\nport=8080 public\nvolume=0777"),cmd("container set-user app-container nonroot","Changed to nonroot.","set-nonroot"),cmd("container remove-secret app-container","Fake secret removed.","remove-secret"),cmd("container close-port app-container 8080","Debug port closed.","close-container-port"),cmd("container fix-permissions app-container","Volume permissions reduced.","fix-volume-permissions")],"Intermediate"),
lab("M4",6,"Compute Hardening","Compute hardening baseline","Apply a full hardening checklist and generate a score.","A virtual server has six baseline weaknesses.",[
 cmd("harden status","unused-service ON\nunused-port OPEN\ndefault-account ON\nupdates PENDING\npermissions WEAK\nlogging OFF"),cmd("harden disable-unused-service","Disabled.","disable-service"),cmd("harden close-unused-port","Closed.","close-unused-port"),cmd("harden remove-default-account","Removed.","remove-default-account"),cmd("harden apply-updates","Virtual updates applied.","apply-updates"),cmd("harden fix-permissions","Permissions corrected.","harden-permissions"),cmd("harden enable-logging","Logging enabled.","enable-logging")],"Intermediate")]
