from .lab_defs_common import lab,cmd
LABS=[
lab("M2",1,"IAM Users and Groups","IAM users, groups, inherited permissions","Assign virtual users to groups and inspect inherited access.","Alice, Bob, and Charlie need role-aligned membership.",[
 cmd("iam users","alice\nbob\ncharlie"),cmd("iam groups","admins\ndevelopers\nauditors"),cmd("iam group-add alice developers","alice added to developers.","alice-developer"),cmd("iam group-add bob auditors","bob added to auditors.","bob-auditor"),cmd("iam group-add charlie admins","charlie added to admins.","charlie-admin"),cmd("iam permissions alice","project.read, app.restart, logs.read")]),
lab("M2",2,"Roles and Policies","Roles, policies, and access evaluation","Attach least-privilege policies and test effective access.","Reusable policies protect compute, storage, and audit duties.",[
 cmd("iam policy list","StorageReadOnly\nStorageAdmin\nComputeOperator\nAuditViewer"),cmd("iam role list","developer-role\nauditor-role"),cmd("iam attach-policy developer-role ComputeOperator","Policy attached.","attach-compute-policy"),cmd("iam attach-policy auditor-role AuditViewer","Policy attached.","attach-audit-policy"),cmd("iam check-access auditor logs.read","ALLOW (simulated)","check-audit-access")]),
lab("M2",3,"Least Privilege","Least privilege","Reduce an overprivileged developer to only required actions.","Developer has admin but only needs project read, app restart, and log read.",[
 cmd("iam permissions developer","* (overprivileged)"),cmd("iam revoke developer admin","Wildcard removed.","remove-admin"),cmd("iam grant developer project.read","Granted.","grant-project-read"),cmd("iam grant developer app.restart","Granted.","grant-app-restart"),cmd("iam grant developer logs.read","Granted.","grant-logs-read")]),
lab("M2",4,"Access Keys","Sandbox API access keys, rotation, revocation","Practice key lifecycle using fake sandbox credentials only.","A service account has an old active fake key.",[
 cmd("keys list","AKIA-LAB-OLD active age=190d (FAKE)"),cmd("keys create service-app","Created FAKE AKIA-LAB-NEW / SECRET-LAB-ONLY.","create-key"),cmd("keys disable AKIA-LAB-OLD","Old fake key disabled.","disable-old-key"),cmd("keys rotate service-app","Rotation complete.","rotate-key"),cmd("keys delete AKIA-LAB-OLD","Old fake key deleted.","delete-old-key")]),
lab("M2",5,"Permission Management","Resource permission matrix","Grant the minimum permissions required by each identity.","Database, storage, application, and logs require different access.",[
 cmd("access matrix","developer: admin everywhere\nauditor: none\nbackup-service: none"),cmd("access grant developer application restart","Granted.","developer-app"),cmd("access grant auditor logs read","Granted.","auditor-logs"),cmd("access grant backup-service storage write","Granted.","backup-storage"),cmd("access revoke developer wildcard","Wildcard revoked.","remove-wildcard")]),
lab("M2",6,"IAM Misconfiguration","IAM security auditing","Find and fix four intentional IAM misconfigurations.","Wildcard admin, dormant privilege, public fake credential, and overprivileged service account exist.",[
 cmd("iam audit","HIGH developer=*\nHIGH dormant-admin\nHIGH public fake credential\nMEDIUM service-backup=*"),cmd("iam fix developer-wildcard","Fixed.","fix-developer-wildcard"),cmd("iam fix dormant-admin","Disabled.","fix-dormant-admin"),cmd("iam fix public-credential","Revoked.","fix-public-credential"),cmd("iam fix service-account","Reduced to storage.write.","fix-service-account")])]
