from .lab_defs_common import lab,cmd
LABS=[
lab("M5",1,"Object Storage Security","S3-style object storage security","Inspect bucket policies and identify sensitive storage.","Three sandbox buckets have different purposes and exposure levels.",[
 cmd("bucket list","public-assets public\ncustomer-data private\nbackup-data private"),cmd("bucket policy customer-data","deny public; allow data-team read/write","inspect-customer-policy"),cmd("bucket access backup-data","backup-service write; auditor read","inspect-backup-access"),cmd("bucket objects customer-data","customers-demo.csv (fictional)","inspect-objects")],"Intermediate"),
lab("M5",2,"Public Bucket Exposure","Public object storage exposure","Detect and remove public access from a vulnerable bucket.","customer-data contains fictional demo records but is accidentally public.",[
 cmd("security scan","HIGH bucket customer-data is public"),cmd("bucket private customer-data","Public access disabled.","disable-public-bucket"),cmd("bucket access customer-data","public=DENY; data-team=ALLOW","verify-private-bucket")],"Intermediate"),
lab("M5",3,"Bucket Permissions","Minimum bucket permissions","Apply least privilege for developer, backup-service, and auditor.","Each identity needs only job-specific access.",[
 cmd("bucket permissions","developer=*\nbackup-service=*\nauditor=*"),cmd("bucket grant developer read","developer=read.","developer-read"),cmd("bucket grant backup-service write","backup-service=write.","backup-write"),cmd("bucket grant auditor read","auditor=read.","auditor-read"),cmd("bucket remove-wildcards","Wildcards removed.","remove-bucket-wildcards")],"Intermediate"),
lab("M5",4,"Encryption","Encryption at rest/in transit concepts","Convert sandbox data from plaintext to encrypted state and enable transport protection.","A fictional confidential report is unencrypted.",[
 cmd("crypto status","confidential.txt at-rest=plaintext transit=http"),cmd("crypto encrypt confidential.txt","Encrypted with LAB-KEY-1.","encrypt-at-rest"),cmd("crypto enable-tls","Simulated transport changed to TLS.","enable-transit-encryption"),cmd("crypto key-rotate LAB-KEY-1","Lab-only key rotated to LAB-KEY-2.","rotate-lab-key")],"Intermediate"),
lab("M5",5,"Data Protection","Data classification and access","Classify fictional data and apply suitable access levels.","NovaCloud has public, internal, confidential, and restricted datasets.",[
 cmd("data list","website-logo\nstaff-handbook\ncustomer-contracts\npayment-demo"),cmd("classify website-logo public","Public.","classify-public"),cmd("classify staff-handbook internal","Internal.","classify-internal"),cmd("classify customer-contracts confidential","Confidential.","classify-confidential"),cmd("classify payment-demo restricted","Restricted.","classify-restricted"),cmd("data apply-policy","Access policies applied.","apply-data-policy")],"Intermediate"),
lab("M5",6,"Snapshots & Recovery","Snapshots and recovery","Create a sandbox snapshot, change data, delete a file, and restore it.","A virtual storage set must recover from accidental deletion.",[
 cmd("file list","config.txt\nreport.txt\narchive.txt"),cmd("snapshot create baseline","Snapshot baseline created.","create-snapshot"),cmd("file modify report.txt","report.txt modified.","modify-file"),cmd("file delete archive.txt","archive.txt deleted.","delete-file"),cmd("snapshot restore baseline","Snapshot restored; archive.txt recovered.","restore-snapshot")],"Intermediate")]
