from .lab_defs_common import lab,cmd
LABS=[
lab("M1",1,"Cloud Environment Fundamentals","Cloud Computing Fundamentals / IaaS, PaaS, SaaS","Identify compute, storage, networking, and identity resources.","A new NovaCloud tenant contains four unlabeled resource types.",[
 cmd("cloud-lab resources","compute: vm-web\nstorage: bucket-assets\nnetwork: vnet-main\nidentity: user-analyst"),
 cmd("answer compute vm-web","Correct: vm-web is compute.","identify-compute"),cmd("answer storage bucket-assets","Correct: bucket-assets is storage.","identify-storage"),cmd("answer network vnet-main","Correct: vnet-main is networking.","identify-network"),cmd("answer identity user-analyst","Correct: user-analyst is identity.","identify-identity")]),
lab("M1",2,"Shared Responsibility Model","Shared responsibility across IaaS, PaaS, SaaS","Classify provider, customer, and shared responsibilities.","Three workloads use different cloud service models.",[
 cmd("responsibility show","IaaS OS=customer; PaaS runtime=provider; SaaS identity=customer; network/data may be shared by model"),cmd("responsibility set iaas operating-system customer","Correct.","classify-iaas-os"),cmd("responsibility set paas runtime provider","Correct.","classify-paas-runtime"),cmd("responsibility set saas identity customer","Correct.","classify-saas-identity")]),
lab("M1",3,"Cloud IAM Fundamentals","Cloud IAM fundamentals","Inspect virtual users, roles, and effective permissions.","Four identities have different access to lab resources.",[
 cmd("iam users","admin\ndeveloper\nanalyst\nviewer"),cmd("iam roles","AdminFull\nDeveloperBuild\nAnalystRead\nViewerRead"),cmd("iam permissions developer","compute.start, compute.stop, logs.read"),cmd("iam permissions viewer","storage.read","inspect-viewer"),cmd("iam permissions admin","*","inspect-admin")]),
lab("M1",4,"Cloud Networking Fundamentals","IP, subnet, gateway, routing, public/private networks","Inspect a virtual network and test sandbox connectivity.","Two servers sit in separate simulated subnets.",[
 cmd("network show","vnet-main 10.10.0.0/16\nsubnet-a 10.10.1.0/24 public\nsubnet-b 10.10.2.0/24 private\ngateway 10.10.0.1"),cmd("network hosts","server-a 10.10.1.10\nserver-b 10.10.2.20"),cmd("network routes","0.0.0.0/0 -> gateway\n10.10.0.0/16 -> local"),cmd("ping server-a","simulated reply from 10.10.1.10","test-public-host"),cmd("ping server-b","simulated reply from 10.10.2.20","test-private-host")]),
lab("M1",5,"Cloud Storage Fundamentals","Object/file storage, permissions, data exposure","Create virtual storage, upload fictional data, and make it private.","A project needs a private object store.",[
 cmd("storage list","public-assets public\nproject-reports private"),cmd("storage create secure-reports","Created secure-reports.","create-storage"),cmd("storage upload secure-reports report.txt","Uploaded fictional report.txt.","upload-object"),cmd("storage permissions secure-reports private","secure-reports is private.","protect-storage")]),
lab("M1",6,"Cloud Security Tools","IAM checker, LAB port scanner, config scanner, log viewer","Use multiple sandbox security tools to identify findings.","NovaCloud requests a baseline assessment.",[
 cmd("security scan","HIGH public storage bucket\nMEDIUM overprivileged user\nLOW unused account"),cmd("security scan iam","developer has wildcard permission.","scan-iam"),cmd("security scan ports","web-01: 80,443,3306 exposed.","scan-ports"),cmd("security scan config","public-assets is public.","scan-config"),cmd("logs show","AUTH_SUCCESS user=analyst\nCONFIG_CHANGE resource=public-assets","inspect-logs")])]
